spring:
  application:
    name: ecom-application
  datasource: 
    url: jdbc:postgresql://localhost:5433/ecommerce1
    username: postgres
    password: 1234
   
  jpa:
    database: postgresql
    show-sql: true    
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
#  h2:
#    console:
#      enabled: 'true'
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
server:
  port: '8081'
  shutdown: graceful

# ver todos lo enpoints de actuator, acá como ejemplo, pero no sedeben habilitar todos innecesariamente:  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted  # no se usa en produccion
  info:
    env:
      enabled: true      
      
info:
  app:
    name: MyNewApp
    description: App built by us
        
  